/**
 * Laendercode (code_3 aus sta_country) -> ISO-3166-1-alpha-2 fuer die
 * Flaggen-Icons (flag-icons, Klasse `fi fi-xx`).
 *
 * Die Codes des Spiels sind gemischt: teils IOC-Kuerzel (GER, SUI, NED),
 * teils ISO-alpha-3 (DZA, BIH, AGO). Eine Ableitung aus den ersten beiden
 * Buchstaben geht deshalb regelmaessig daneben — AND (Andorra) waere 'an'
 * (Niederlaendische Antillen), GER waere 'ge' (Georgien). Nur diese Tabelle
 * ist verbindlich.
 *
 * Die Tabelle deckt ALLE 138 Laender aus sta_country ab. Frueher standen hier
 * nur die rund 50 Radsportnationen; Fahrer aus den uebrigen Laendern — und die
 * Newgen-Erzeugung wuerfelt sie aus dem ganzen Bestand — blieben ohne Flagge.
 *
 * Einzige bewusste Auslassung ist OTH ("Sonstige"), das auf die neutrale
 * UN-Flagge zeigt.
 */
export const FLAG_CODE_BY_CODE3: Record<string, string> = {
  // ---- Europa ----
  ALB: 'al',
  AND: 'ad',
  AUT: 'at',
  BEL: 'be',
  BIH: 'ba',
  BLR: 'by',
  BUL: 'bg',
  CRO: 'hr',
  CZE: 'cz',
  DEN: 'dk',
  ESP: 'es',
  EST: 'ee',
  FIN: 'fi',
  FRA: 'fr',
  GBR: 'gb',
  GER: 'de',
  GRE: 'gr',
  HUN: 'hu',
  IRE: 'ie',
  IRL: 'ie',
  ISL: 'is',
  ITA: 'it',
  KOS: 'xk',
  LAT: 'lv',
  LIE: 'li',
  LTU: 'lt',
  LUX: 'lu',
  MCO: 'mc',
  MKD: 'mk',
  MNE: 'me',
  MOL: 'md',
  NED: 'nl',
  NOR: 'no',
  POL: 'pl',
  POR: 'pt',
  ROM: 'ro',
  RUS: 'ru',
  SER: 'rs',
  SLO: 'si',
  SMR: 'sm',
  SUI: 'ch',
  SVK: 'sk',
  SWD: 'se',
  SWI: 'ch',
  UKR: 'ua',

  // ---- Asien ----
  ARM: 'am',
  AZE: 'az',
  BHR: 'bh',
  BRN: 'bn',
  CHI: 'cn',
  CYP: 'cy',
  GEO: 'ge',
  HKG: 'hk',
  IDN: 'id',
  IND: 'in',
  IRN: 'ir',
  IRQ: 'iq',
  ISR: 'il',
  JPN: 'jp',
  KAZ: 'kz',
  KGZ: 'kg',
  KHM: 'kh',
  KOR: 'kr',
  KUW: 'kw',
  LAO: 'la',
  LKA: 'lk',
  MAS: 'my',
  MNG: 'mn',
  PAK: 'pk',
  PHL: 'ph',
  PSE: 'ps',
  QAT: 'qa',
  SAU: 'sa',
  SGP: 'sg',
  SYR: 'sy',
  THA: 'th',
  TLS: 'tl',
  TUR: 'tr',
  TWN: 'tw',
  UAE: 'ae',
  UZB: 'uz',
  VNM: 'vn',

  // ---- Afrika ----
  AGO: 'ao',
  BEN: 'bj',
  BFA: 'bf',
  CIV: 'ci',
  CMR: 'cm',
  COD: 'cd',
  DZA: 'dz',
  EGY: 'eg',
  ERI: 'er',
  ETH: 'et',
  GAB: 'ga',
  GHA: 'gh',
  KEN: 'ke',
  LSO: 'ls',
  MAR: 'ma',
  MLI: 'ml',
  MLT: 'mt',
  MUS: 'mu',
  NAM: 'na',
  NGA: 'ng',
  RSA: 'za',
  RWA: 'rw',
  SAR: 'za',
  SEN: 'sn',
  TUN: 'tn',
  UGA: 'ug',
  ZIM: 'zw',

  // ---- Nordamerika ----
  BER: 'bm',
  BHS: 'bs',
  BLZ: 'bz',
  CAN: 'ca',
  CRC: 'cr',
  CUB: 'cu',
  CUW: 'cw',
  DOM: 'do',
  GRD: 'gd',
  GTM: 'gt',
  HND: 'hn',
  JAM: 'jm',
  MEX: 'mx',
  PAN: 'pa',
  PRI: 'pr',
  TTO: 'tt',
  USA: 'us',

  // ---- Suedamerika ----
  ARG: 'ar',
  BOL: 'bo',
  BRA: 'br',
  CHL: 'cl',
  COL: 'co',
  ECU: 'ec',
  GUY: 'gy',
  PER: 'pe',
  PRY: 'py',
  URU: 'uy',
  VEN: 've',

  // ---- Ozeanien ----
  AUS: 'au',
  GUM: 'gu',
  NZL: 'nz',

  // ---- Sonstige ----
  OMA: 'om',
  OTH: 'un',
};
